const NOTIFICATION = {
	RESET_PASSWORD: "RESET_PASSWORD",
	VERIFY_WORKER: "VERIFY_WORKER",
	VERIFIED_WORKER: "VERIFIED_WORKER",
	PLACED_ORDER: "PLACED_ORDER",
	CANCEL_ORDER: "CANCEL_ORDER",
	DISPATCHED_ORDER: "DISPATCHED_ORDER",
	DELIVERED_ORDER: "DELIVERED_ORDER",
};

module.exports = NOTIFICATION;
